/** * Reads SSM environment context from a known Amplify environment variable, * fetches values from SSM and places those values in the corresponding environment variables */export const internalAmplifyFunctionResolveSsmParams = async (client) => {    const envPathObject = JSON.parse(process.env.AMPLIFY_SSM_ENV_CONFIG ?? '{}');    const paths = Object.values(envPathObject).map((paths) => paths.path);    if (paths.length === 0) {        return;    }    let actualSsmClient;    if (client) {        actualSsmClient = client;    }    else {        const ssmSdk = await import('@aws-sdk/client-ssm');        actualSsmClient = new ssmSdk.SSM();    }    const chunkArray = (array, chunkSize) => {        const chunks = [];        for (let i = 0; i < array.length; i += chunkSize) {            chunks.push(array.slice(i, i + chunkSize));        }        return chunks;    };    const resolveSecrets = async (paths) => {        const response = (await Promise.all(chunkArray(paths, 10).map(async (chunkedPaths) => await actualSsmClient.getParameters({            Names: chunkedPaths,            WithDecryption: true,        })))).reduce((accumulator, res) => {            accumulator.Parameters?.push(...(res.Parameters ?? []));            accumulator.InvalidParameters?.push(...(res.InvalidParameters ?? []));            return accumulator;        }, {            Parameters: [],            InvalidParameters: [],        });        if (response.Parameters && response.Parameters.length > 0) {            for (const parameter of response.Parameters) {                if (parameter.Name) {                    const envKey = Object.keys(envPathObject).find((key) => envPathObject[key].sharedPath === parameter.Name ||                        envPathObject[key].path === parameter.Name);                    if (envKey) {                        process.env[envKey] = parameter.Value;                    }                }            }        }        return response;    };    const response = await resolveSecrets(paths);    const sharedPaths = (response?.InvalidParameters || [])        .map((invalidParam) => Object.values(envPathObject).find((paths) => paths.path === invalidParam)?.sharedPath)        .filter((sharedParam) => !!sharedParam);     if (sharedPaths.length > 0) {        await resolveSecrets(sharedPaths);    }};await internalAmplifyFunctionResolveSsmParams();const SSM_PARAMETER_REFRESH_MS = 1000 * 60;setInterval(async () => {    try {        await internalAmplifyFunctionResolveSsmParams();    }    catch (error) {        try {                        console.debug(error);                    }        catch {                    }    }}, SSM_PARAMETER_REFRESH_MS);export {};
import{createRequire as d}from"node:module";import g from"node:path";import h from"node:url";global.require=d(import.meta.url);global.__filename=h.fileURLToPath(import.meta.url);global.__dirname=g.dirname(__filename);exports.handler=async r=>{if(r.requestContext&&r.requestContext.http&&r.requestContext.http.method==="OPTIONS")return t(200,{ok:!0});try{let e=process.env.OPENAI_API_KEY;if(!e)return t(500,{error:"OPENAI_API_KEY not set"});let n={};try{typeof r.body=="string"?n=JSON.parse(r.body):r.body&&(n=r.body)}catch(m){return console.log("Failed to parse body:",m),t(400,{error:"Invalid JSON body"})}let a=(n.resumeText||"").toString(),c=(n.jobDescription||"").toString(),s=(n.language||"en").toString();if(!a.trim())return t(400,{error:"resumeText is required"});let l=s==="es"?"Eres un experto en redacci\xF3n de curr\xEDculums. Reescribe el curr\xEDculum del usuario en un formato claro, profesional y enfocado en logros. Usa vi\xF1etas cuando sea apropiado. Mant\xE9n el contenido apto para sistemas ATS.":"You are an expert resume writer. Rewrite the user's resume into a clear, professional, achievement-focused format. Use bullet points where appropriate. Keep the content ATS-friendly.",u=(s==="es"?`Curr\xEDculum original:

`:`Original resume:

`)+a+`

`+(c?(s==="es"?`Descripci\xF3n del puesto objetivo:

`:`Target job description:

`)+c+`

`:"")+(s==="es"?"Reescribe el curr\xEDculum para que se alinee con el puesto (si se proporcion\xF3), manteniendo la veracidad de la informaci\xF3n. Devu\xE9lvelo en texto plano.":"Rewrite the resume so it aligns with the target role (if provided), keeping all facts true. Return plain text only."),i=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${e}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4.1-mini",messages:[{role:"system",content:l},{role:"user",content:u}],temperature:.4})}),o=await i.json();if(!i.ok)return console.error("OpenAI error:",i.status,o),t(502,{error:"OpenAI API error",status:i.status,details:o});let p=o.choices&&o.choices[0]&&o.choices[0].message&&o.choices[0].message.content?o.choices[0].message.content.trim():s==="es"?"No se pudo generar una respuesta.":"No response generated.";return t(200,{rewrittenText:p})}catch(e){return console.error("rewriteResume unexpected error:",e),t(500,{error:"Internal server error",details:e&&e.message?e.message:String(e)})}};function t(r,e){return{statusCode:r,headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"*","Access-Control-Allow-Methods":"OPTIONS,POST"},body:JSON.stringify(e)}}
//# sourceMappingURL=index.mjs.map
